# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = C:\mingw64\bin\cmake.exe

# The command to remove a file.
RM = C:\mingw64\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\SDL2_Project\TinyFootballArena

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\SDL2_Project\TinyFootballArena

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	C:\mingw64\bin\cmake.exe -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	C:\mingw64\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\SDL2_Project\TinyFootballArena\CMakeFiles D:\SDL2_Project\TinyFootballArena\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\SDL2_Project\TinyFootballArena\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P D:\SDL2_Project\TinyFootballArena\CMakeFiles\VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TinyFootballArena

# Build rule for target.
TinyFootballArena: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 TinyFootballArena
.PHONY : TinyFootballArena

# fast build rule for target.
TinyFootballArena/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TinyFootballArena.dir\build.make CMakeFiles/TinyFootballArena.dir/build
.PHONY : TinyFootballArena/fast

src/core/App.obj: src/core/App.cpp.obj
.PHONY : src/core/App.obj

# target to build an object file
src/core/App.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TinyFootballArena.dir\build.make CMakeFiles/TinyFootballArena.dir/src/core/App.cpp.obj
.PHONY : src/core/App.cpp.obj

src/core/App.i: src/core/App.cpp.i
.PHONY : src/core/App.i

# target to preprocess a source file
src/core/App.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TinyFootballArena.dir\build.make CMakeFiles/TinyFootballArena.dir/src/core/App.cpp.i
.PHONY : src/core/App.cpp.i

src/core/App.s: src/core/App.cpp.s
.PHONY : src/core/App.s

# target to generate assembly for a file
src/core/App.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TinyFootballArena.dir\build.make CMakeFiles/TinyFootballArena.dir/src/core/App.cpp.s
.PHONY : src/core/App.cpp.s

src/core/Config.obj: src/core/Config.cpp.obj
.PHONY : src/core/Config.obj

# target to build an object file
src/core/Config.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TinyFootballArena.dir\build.make CMakeFiles/TinyFootballArena.dir/src/core/Config.cpp.obj
.PHONY : src/core/Config.cpp.obj

src/core/Config.i: src/core/Config.cpp.i
.PHONY : src/core/Config.i

# target to preprocess a source file
src/core/Config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TinyFootballArena.dir\build.make CMakeFiles/TinyFootballArena.dir/src/core/Config.cpp.i
.PHONY : src/core/Config.cpp.i

src/core/Config.s: src/core/Config.cpp.s
.PHONY : src/core/Config.s

# target to generate assembly for a file
src/core/Config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TinyFootballArena.dir\build.make CMakeFiles/TinyFootballArena.dir/src/core/Config.cpp.s
.PHONY : src/core/Config.cpp.s

src/core/Game.obj: src/core/Game.cpp.obj
.PHONY : src/core/Game.obj

# target to build an object file
src/core/Game.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TinyFootballArena.dir\build.make CMakeFiles/TinyFootballArena.dir/src/core/Game.cpp.obj
.PHONY : src/core/Game.cpp.obj

src/core/Game.i: src/core/Game.cpp.i
.PHONY : src/core/Game.i

# target to preprocess a source file
src/core/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TinyFootballArena.dir\build.make CMakeFiles/TinyFootballArena.dir/src/core/Game.cpp.i
.PHONY : src/core/Game.cpp.i

src/core/Game.s: src/core/Game.cpp.s
.PHONY : src/core/Game.s

# target to generate assembly for a file
src/core/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TinyFootballArena.dir\build.make CMakeFiles/TinyFootballArena.dir/src/core/Game.cpp.s
.PHONY : src/core/Game.cpp.s

src/core/Input.obj: src/core/Input.cpp.obj
.PHONY : src/core/Input.obj

# target to build an object file
src/core/Input.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TinyFootballArena.dir\build.make CMakeFiles/TinyFootballArena.dir/src/core/Input.cpp.obj
.PHONY : src/core/Input.cpp.obj

src/core/Input.i: src/core/Input.cpp.i
.PHONY : src/core/Input.i

# target to preprocess a source file
src/core/Input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TinyFootballArena.dir\build.make CMakeFiles/TinyFootballArena.dir/src/core/Input.cpp.i
.PHONY : src/core/Input.cpp.i

src/core/Input.s: src/core/Input.cpp.s
.PHONY : src/core/Input.s

# target to generate assembly for a file
src/core/Input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TinyFootballArena.dir\build.make CMakeFiles/TinyFootballArena.dir/src/core/Input.cpp.s
.PHONY : src/core/Input.cpp.s

src/ecs/Goal.obj: src/ecs/Goal.cpp.obj
.PHONY : src/ecs/Goal.obj

# target to build an object file
src/ecs/Goal.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TinyFootballArena.dir\build.make CMakeFiles/TinyFootballArena.dir/src/ecs/Goal.cpp.obj
.PHONY : src/ecs/Goal.cpp.obj

src/ecs/Goal.i: src/ecs/Goal.cpp.i
.PHONY : src/ecs/Goal.i

# target to preprocess a source file
src/ecs/Goal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TinyFootballArena.dir\build.make CMakeFiles/TinyFootballArena.dir/src/ecs/Goal.cpp.i
.PHONY : src/ecs/Goal.cpp.i

src/ecs/Goal.s: src/ecs/Goal.cpp.s
.PHONY : src/ecs/Goal.s

# target to generate assembly for a file
src/ecs/Goal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TinyFootballArena.dir\build.make CMakeFiles/TinyFootballArena.dir/src/ecs/Goal.cpp.s
.PHONY : src/ecs/Goal.cpp.s

src/ecs/Goalkeeper.obj: src/ecs/Goalkeeper.cpp.obj
.PHONY : src/ecs/Goalkeeper.obj

# target to build an object file
src/ecs/Goalkeeper.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TinyFootballArena.dir\build.make CMakeFiles/TinyFootballArena.dir/src/ecs/Goalkeeper.cpp.obj
.PHONY : src/ecs/Goalkeeper.cpp.obj

src/ecs/Goalkeeper.i: src/ecs/Goalkeeper.cpp.i
.PHONY : src/ecs/Goalkeeper.i

# target to preprocess a source file
src/ecs/Goalkeeper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TinyFootballArena.dir\build.make CMakeFiles/TinyFootballArena.dir/src/ecs/Goalkeeper.cpp.i
.PHONY : src/ecs/Goalkeeper.cpp.i

src/ecs/Goalkeeper.s: src/ecs/Goalkeeper.cpp.s
.PHONY : src/ecs/Goalkeeper.s

# target to generate assembly for a file
src/ecs/Goalkeeper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TinyFootballArena.dir\build.make CMakeFiles/TinyFootballArena.dir/src/ecs/Goalkeeper.cpp.s
.PHONY : src/ecs/Goalkeeper.cpp.s

src/ecs/Player.obj: src/ecs/Player.cpp.obj
.PHONY : src/ecs/Player.obj

# target to build an object file
src/ecs/Player.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TinyFootballArena.dir\build.make CMakeFiles/TinyFootballArena.dir/src/ecs/Player.cpp.obj
.PHONY : src/ecs/Player.cpp.obj

src/ecs/Player.i: src/ecs/Player.cpp.i
.PHONY : src/ecs/Player.i

# target to preprocess a source file
src/ecs/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TinyFootballArena.dir\build.make CMakeFiles/TinyFootballArena.dir/src/ecs/Player.cpp.i
.PHONY : src/ecs/Player.cpp.i

src/ecs/Player.s: src/ecs/Player.cpp.s
.PHONY : src/ecs/Player.s

# target to generate assembly for a file
src/ecs/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TinyFootballArena.dir\build.make CMakeFiles/TinyFootballArena.dir/src/ecs/Player.cpp.s
.PHONY : src/ecs/Player.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TinyFootballArena.dir\build.make CMakeFiles/TinyFootballArena.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TinyFootballArena.dir\build.make CMakeFiles/TinyFootballArena.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TinyFootballArena.dir\build.make CMakeFiles/TinyFootballArena.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/scene/MatchScene.obj: src/scene/MatchScene.cpp.obj
.PHONY : src/scene/MatchScene.obj

# target to build an object file
src/scene/MatchScene.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TinyFootballArena.dir\build.make CMakeFiles/TinyFootballArena.dir/src/scene/MatchScene.cpp.obj
.PHONY : src/scene/MatchScene.cpp.obj

src/scene/MatchScene.i: src/scene/MatchScene.cpp.i
.PHONY : src/scene/MatchScene.i

# target to preprocess a source file
src/scene/MatchScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TinyFootballArena.dir\build.make CMakeFiles/TinyFootballArena.dir/src/scene/MatchScene.cpp.i
.PHONY : src/scene/MatchScene.cpp.i

src/scene/MatchScene.s: src/scene/MatchScene.cpp.s
.PHONY : src/scene/MatchScene.s

# target to generate assembly for a file
src/scene/MatchScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TinyFootballArena.dir\build.make CMakeFiles/TinyFootballArena.dir/src/scene/MatchScene.cpp.s
.PHONY : src/scene/MatchScene.cpp.s

src/sys/Physics.obj: src/sys/Physics.cpp.obj
.PHONY : src/sys/Physics.obj

# target to build an object file
src/sys/Physics.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TinyFootballArena.dir\build.make CMakeFiles/TinyFootballArena.dir/src/sys/Physics.cpp.obj
.PHONY : src/sys/Physics.cpp.obj

src/sys/Physics.i: src/sys/Physics.cpp.i
.PHONY : src/sys/Physics.i

# target to preprocess a source file
src/sys/Physics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TinyFootballArena.dir\build.make CMakeFiles/TinyFootballArena.dir/src/sys/Physics.cpp.i
.PHONY : src/sys/Physics.cpp.i

src/sys/Physics.s: src/sys/Physics.cpp.s
.PHONY : src/sys/Physics.s

# target to generate assembly for a file
src/sys/Physics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TinyFootballArena.dir\build.make CMakeFiles/TinyFootballArena.dir/src/sys/Physics.cpp.s
.PHONY : src/sys/Physics.cpp.s

src/ui/HUD.obj: src/ui/HUD.cpp.obj
.PHONY : src/ui/HUD.obj

# target to build an object file
src/ui/HUD.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TinyFootballArena.dir\build.make CMakeFiles/TinyFootballArena.dir/src/ui/HUD.cpp.obj
.PHONY : src/ui/HUD.cpp.obj

src/ui/HUD.i: src/ui/HUD.cpp.i
.PHONY : src/ui/HUD.i

# target to preprocess a source file
src/ui/HUD.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TinyFootballArena.dir\build.make CMakeFiles/TinyFootballArena.dir/src/ui/HUD.cpp.i
.PHONY : src/ui/HUD.cpp.i

src/ui/HUD.s: src/ui/HUD.cpp.s
.PHONY : src/ui/HUD.s

# target to generate assembly for a file
src/ui/HUD.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TinyFootballArena.dir\build.make CMakeFiles/TinyFootballArena.dir/src/ui/HUD.cpp.s
.PHONY : src/ui/HUD.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... TinyFootballArena
	@echo ... src/core/App.obj
	@echo ... src/core/App.i
	@echo ... src/core/App.s
	@echo ... src/core/Config.obj
	@echo ... src/core/Config.i
	@echo ... src/core/Config.s
	@echo ... src/core/Game.obj
	@echo ... src/core/Game.i
	@echo ... src/core/Game.s
	@echo ... src/core/Input.obj
	@echo ... src/core/Input.i
	@echo ... src/core/Input.s
	@echo ... src/ecs/Goal.obj
	@echo ... src/ecs/Goal.i
	@echo ... src/ecs/Goal.s
	@echo ... src/ecs/Goalkeeper.obj
	@echo ... src/ecs/Goalkeeper.i
	@echo ... src/ecs/Goalkeeper.s
	@echo ... src/ecs/Player.obj
	@echo ... src/ecs/Player.i
	@echo ... src/ecs/Player.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/scene/MatchScene.obj
	@echo ... src/scene/MatchScene.i
	@echo ... src/scene/MatchScene.s
	@echo ... src/sys/Physics.obj
	@echo ... src/sys/Physics.i
	@echo ... src/sys/Physics.s
	@echo ... src/ui/HUD.obj
	@echo ... src/ui/HUD.i
	@echo ... src/ui/HUD.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P D:\SDL2_Project\TinyFootballArena\CMakeFiles\VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

